# permissions for end users to edit charmedk8sconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: charmedk8sconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-bootstrap-provider-charmed-k8s
    app.kubernetes.io/part-of: cluster-api-bootstrap-provider-charmed-k8s
    app.kubernetes.io/managed-by: kustomize
  name: charmedk8sconfig-editor-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - charmedk8sconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - charmedk8sconfigs/status
  verbs:
  - get
