apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: CharmedK8sConfigTemplate
metadata:
  name: "sample-template"
spec:
  template:
    spec:
      workerApplications:
        - kubernetes-worker

      