name: Integration Tests
on: [pull_request]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup env
      run: test/integration/setup-env.sh
    - name: Run tests
      run: test/integration/run.sh
